### ISSUE TITLE
Encountered an error while running the script in the Verification 

### ISSUE THREAD

**Issue by cookiegg** [Verified-Intelligence/Lyapunov_Stable_NN_Controllers#1]
Hello, I encountered the following errors while running the script 
```shell
python abcrown.py --config $CONFIG_PATH/path_tracking_state_feedback_lyapunov_in_levelset.yaml
```
Could you please give me some hints on how to resolve them?

**the errors info**
```shell
Traceback (most recent call last):
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/abcrown.py", line 611, in <module>
    abcrown = ABCROWN(args=sys.argv[1:])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/abcrown.py", line 49, in __init__
    arguments.Config.parse_config(args)
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/arguments.py", line 953, in parse_config
    self.update_config_dict(self.all_args, loaded_args)
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/arguments.py", line 890, in update_config_dict
    self.update_config_dict(old_args_dict, new_args_dict[k],
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/arguments.py", line 890, in update_config_dict
    self.update_config_dict(old_args_dict, new_args_dict[k],
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/arguments.py", line 890, in update_config_dict
    self.update_config_dict(old_args_dict, new_args_dict[k],
  [Previous line repeated 1 more time]
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/arguments.py", line 894, in update_config_dict
    self.set_dict_by_hierarchy(old_args_dict, levels, new_args_dict,
  File "/data/cbf/Lyapunov_Stable_NN_Controllers/alpha-beta-CROWN/complete_verifier/arguments.py", line 868, in set_dict_by_hierarchy
    raise ValueError(f"Config key {h} not found!")
ValueError: Config key ['bab', 'branching', 'input_split', 'sb_coeff_thresh'] not found!
```

**Comment by huanzhang12** [comment]
@cookiegg Thank you for trying our new code so quickly! Our code depends on a new version of the alpha-beta-CROWN verifier, which is planned to be released today. You can keep an eye on it here: https://github.com/Verified-Intelligence/alpha-beta-CROWN, and the new version will be pushed later today. Then the examples should run smoothly.

**Comment by cookiegg** [comment]
Haha, I happened to stumble upon your paper on arXiv and found it fascinating. I greatly appreciate you making the code open-source and for your prompt response.

**Comment by huanzhang12** [comment]
@cookiegg I've tested the latest release of alpha-beta-CROWN and things should be working now. Let me know if you have any additional questions.

**Comment by cookiegg** [comment]
I have followed the tutorial and executed the following code:
```python
python abcrown.py --config $CONFIG_PATH/pendulum_output_feedback_lyapunov_in_levelset.yaml
```
The output is: 

![image](https://github.com/Verified-Intelligence/Lyapunov_Stable_NN_Controllers/assets/11715325/10d88f79-b791-4a40-8a09-884d146ab386)

 and it seems that everything is normal. Thank you very much for your help.
